sonar.projectKey=ammar49-cyber_arixalgo
sonar.organization=ammar49-cyber
sonar.projectName=ARIX-Algo
sonar.projectVersion=0.1.1
sonar.language=c
sonar.sourceEncoding=UTF-8
sonar.sources=include,kernel,algorithms,lib,security
sonar.exclusions=build/**,target/**,releases/**
sonar.tests=tests
sonar.test.exclusions=tests/benchmark/**
sonar.c.compiler.parser=GCC
sonar.c.compiler.charset=UTF-8
sonar.c.errorRecoveryEnabled=true
sonar.c.file.suffixes=.c,.h
sonar.cfamily.analysisCache.memoryBoundary=512
