from .. import _neural_engine_bridge

__version__ = "0.9.5.748"

# Phase 1 Foundation — dispatch layer + ctypes utilities
from . import dispatch
from .dispatch import (
    get_backend,
    get_security_backend,
    get_algo_backend,
    get_kernel_backend,
    get_infra_backend,
    _HAS_CUDA,
    _HAS_C,
)
from .c_loader import load_library, find_load
from .c_types import (
    int8_t,
    uint8_t,
    int16_t,
    uint16_t,
    int32_t,
    uint32_t,
    int64_t,
    uint64_t,
    size_t,
    ssize_t,
    float_t,
    double_t,
    const_char_p,
    void_p,
    DataBuffer,
    make_struct,
)

# Phase 2 — Crypto bindings
from .crypto_sign import Ed25519, Dilithium, SphincsPlus
from .crypto_kem import KyberKEM, X25519
from .crypto_symmetric import AESGCM, ChaCha20, Poly1305, AEAD
from .crypto_hash import sha256, sha512, sha3_256, sha3_512, shake_128, shake_256, Blake3, SipHash
from .crypto_kdf import HMAC as HMAC_, HKDF, PBKDF2, Argon2
from .crypto_util import BigNum, DRBG, Random, ConstantTime, EntropyPool

# Phase 3 — Security bindings (S1–S9)
from .secure_memory import (
    SecureAllocator, StackCanary, ASLR, MemoryHardening, MemoryLeakDetector,
)
from .s4_network import DDoSMitigation, IdentityManager, TransportSecurity
from .runtime_monitor import IntegrityMonitor, ContainerBreakoutDetector, AdvancedMonitor
from .key_vault import KeyVault, AuditLogger
from .secure_updates import SignedUpdate, ContainerSecurity
from .formal_verify import LTLProperty, ModelChecker, StateGraph
from .pen_testing import NetworkFuzzer, SelfAuditor
from .obfuscation_bridge import (
    ObfuscationConfig, CfgFlattening, InstructionSubstitution,
    OpaquePredicate, StringEncryption, ObfuscationPipeline,
)
from .ai_safety_ext import RLHFSafety, DataPoisoningDefense
from .ai_safety_ext import PromptFilter as AIPromptFilter
from .ai_safety_ext import OutputVerifier as AIOutputVerifier

# Phase 4 — Algorithm bindings (ARC/FM/HSS/NPE/SER)
from .algo_arc import ARCAttackSim, ARCFForward, ARCGradientObfuscator, ARCInputGuard, ARCOutputVerifier
from .algo_fm import FMController, FMMemoryBank, FMNode, FMSync
from .algo_hss import HSSDiscretize, HSSScan, HSSStep
from .algo_hss import HSSModel as AlgoHSSModel
from .algo_npe import NPEInstruction, NPEProgram, NPECompiler, NPEVM, NPEVerify
from .algo_ser import SERExpert, SERRoute, SERLayer, SERLoss
from .algo_ser import SERModel as AlgoSERModel

# Phase 5 — Kernel bindings
from .c_attention import Attention, DifferentialAttention, FlexAttention
from .c_arch import ArchOps, Mamba2
from .c_memory import MemoryAllocator, MemoryPool
from .c_thread import ThreadPool, WorkStealingPool
from .c_tensor_expr import TensorExpr, TensorExprCompiler
from .c_simd_gemm import SimdGemm, GemmConfig
from .c_logger import Logger

from .tensor import (
    Tensor,
    Dtype,
    Device,
    Layout,
    Tensorable,
    _HAS_C_BACKEND,
)
from .nn import (
    Module,
    Linear,
    Embedding,
    Dropout,
    LayerNorm,
    RMSNorm,
    GELU,
    SiLU,
    ReLU,
    Sigmoid,
    Tanh,
    Sequential,
    MultiheadAttention,
    TransformerBlock,
    Transformer,
)
from .optim import (
    Optimizer,
    SGD,
    AdamW,
    Lion,
    LAMB,
    CosineAnnealingLR,
)
from .data import (
    Dataset,
    TensorDataset,
    TextDataset,
    SimpleTokenizer,
    BatchCollator,
    Preprocessor,
)
from .distributed import (
    DistributedContext,
    DistributedSampler,
    DistributedDataParallel,
    init_process_group,
    destroy_process_group,
    get_world_size,
    get_rank,
    barrier,
    all_reduce,
    launch,
)
from .hf_integration import (
    load_hf_model,
    save_hf_model,
    load_config,
)
from .model import (
    Model,
    ModelConfig,
    HSSModel,
    HSSConfig,
    SERModel,
    SERConfig,
    ARCModel,
    ARCConfig,
    NPEModel,
    NPEConfig,
    FMModel,
    FMConfig,
)
from .quantization import (
    QuantMode,
    QuantGranularity,
    quantize_int8_sym,
    dequantize_int8_sym,
    quantize_int8_asym,
    dequantize_int8_asym,
    quantize_int8_channel,
    dequantize_int8_channel,
    quantize_int4_sym,
    dequantize_int4_sym,
    quantize_fp8_e4m3,
    dequantize_fp8_e4m3,
    quantize_fp8_e5m2,
    dequantize_fp8_e5m2,
    awq_scale_weights,
    awq_quantize,
    gptq_compute_hessian,
    gptq_quantize,
    QuantizedLinear,
    quantize_error,
)
from .amp import autocast, GradScaler
from .schedulers import (
    LRScheduler,
    StepLR,
    ExponentialLR,
    CosineAnnealingLR,
    CosineAnnealingWarmRestarts,
    ConstantLRWithWarmup,
    LinearWarmupCosineDecay,
    PolynomialLR,
    OneCycleLR,
    ReduceLROnPlateau,
    CosineAnnealingWithWarmup,
    SequentialLR,
    ChainedScheduler,
    TriStageLR,
    get_scheduler,
)
from .optim_extra import (
    Lion,
    LAMB,
    LARS,
    AdaFactor,
    RAdam,
    Sophia,
    Adan,
    ScheduleFreeAdamW,
    get_optimizer as get_extra_optimizer,
)
from .optim_advanced import (
    SM3,
    Demeter,
    CaProp,
    SOAP,
    DistributedAdam,
    OrthoAdam,
    get_optimizer as get_advanced_optimizer,
)
from .grad_checkpoint import (
    GradientCheckpointer,
    checkpoint,
    CheckpointSegment,
    checkpoint_sequential,
)
from .data_loader import (
    Dataset,
    TensorDataset,
    MemoryMappedTextDataset,
    DistributedSampler,
    DataLoader,
    default_collate,
    StreamingTokenDataset,
    StreamingTokenDataset,
)
from .profiler import (
    Profiler,
    ProfileEntry,
    Timer,
    MemoryTracker,
    TrainProfiler,
    timeit,
    get_profiler,
)
from .model_zoo import (
    ModelFamily,
    LlamaConfig,
    MistralConfig,
    Qwen2Config,
    DeepSeekV2Config,
    get_model_config,
    config_from_json,
    list_available_models,
    read_safetensors,
    convert_hf_to_sneppx,
    build_model_from_config,
    build_transformer_from_config,
    from_pretrained,
    HF_WEIGHT_MAP,
)
from .model_implementations import (
    BertModel,
    BertForMaskedLM,
    BertConfig,
    GPTModel,
    GPTLMHeadModel,
    GPTConfig,
    T5Model,
    T5ForConditionalGeneration,
    T5Config,
    create_bert_model,
    create_gpt_model,
    create_t5_model,
    get_model_config,
    count_parameters,
    get_model_size_mb,
)
from .advanced_ops import (
    conv2d,
    conv1d,
    max_pool2d,
    avg_pool2d,
    adaptive_avg_pool2d,
    adaptive_max_pool2d,
    rnn_cell,
    lstm_cell,
    gru_cell,
    multi_head_attention,
    transformer_block,
    softmax,
    layernorm,
    rmsnorm,
)
from .augmentation import (
    Compose,
    RandomApply,
    RandomChoice,
    RandomOrder,
    random_resized_crop,
    random_horizontal_flip,
    random_vertical_flip,
    random_rotation,
    color_jitter,
    random_grayscale,
    gaussian_blur,
    solarize,
    posterize,
    auto_contrast,
    equalize,
    invert,
    sharpness,
    mixup,
    cutmix,
    augmix,
    cutout,
    random_erasing,
    random_token_mask,
    random_word_dropout,
    random_word_shuffle,
    token_cutout,
    time_stretch,
    pitch_shift,
    time_mask,
    freq_mask,
    center_crop,
    random_crop,
    five_crop,
    ten_crop,
    IMAGENET_TRAIN_TRANSFORMS,
    IMAGENET_EVAL_TRANSFORMS,
    CIFAR10_TRAIN_TRANSFORMS,
    CIFAR10_EVAL_TRANSFORMS,
)
from .onnx_export import (
    OnnxExporter,
    OnnxImporter,
    OnnxModel,
    OnnxGraph,
    OnnxNode,
    OnnxTensor,
    OnnxInitializer,
    export_onnx,
    import_onnx,
    SNEPPX_TO_ONNX_OP,
    ONNX_OP_REGISTRY,
    TensorRTExporter,
    onnx_validate,
    onnx_version_compatible,
    upgrade_opset,
)
from .amp import autocast, GradScaler
from .grad_checkpoint import checkpoint, GradientCheckpointer
from .schedulers import (
    LRScheduler,
    StepLR,
    ExponentialLR,
    CosineAnnealingLR,
    CosineAnnealingWarmRestarts,
    ConstantLRWithWarmup,
    LinearWarmupCosineDecay,
    PolynomialLR,
    OneCycleLR,
    ReduceLROnPlateau,
    CosineAnnealingWithWarmupRestarts,
    SequentialLR,
    ChainedScheduler,
    TriStageLR,
    get_scheduler,
)
from .optim_extra import (
    Lion,
    LAMB,
    LARS,
    AdaFactor,
    RAdam,
    Sophia,
    Adan,
    ScheduleFreeAdamW,
    get_optimizer as get_extra_optimizer,
)
from .trainer_v2 import UltraTrainConfig, UltraTrainer
from .trainer_v3 import (
    TrainConfig as TrainConfigV3,
    Trainer as TrainerV3,
    clip_grad_norm_,
    estimate_flops,
)
from .checkpoint_manager import CheckpointManager
from .distributed_wrapper import DistributedWrapper
from .experiment_tracker import (
    ExperimentRun,
    LocalBackend,
    Tracker,
    LogTracker,
    ExperimentTracker,
    WandbTracker,
    MLflowTracker,
    CompositeTracker,
)
from .experiment_cli import main as experiment_cli_main
from .hparams import (
    Param,
    UniformFloat,
    LogUniformFloat,
    UniformInt,
    Choice,
    Fixed,
    SearchSpace,
    Trial,
    Sampler,
    GridSampler,
    RandomSampler,
    BayesianSampler,
    HPSearchRunner,
)
from .differential_privacy import (
    LaplaceMech,
    GaussianMech,
    PrivacyBudget,
    RDPAccountant,
    DPSGD,
)
from .adversarial import (
    Attack,
    FGSM,
    PGD,
    AdversarialExample,
    AdversarialTrainer,
)
from .watermark import (
    ModelHasher,
    WeightWatermark,
    BackdoorWatermark,
)
from .s5_safety import (
    S5PromptFilter,
    S5OutputVerifier,
    S5RLHFSafety,
)
from .security_middleware import (
    AuthConfig,
    RateLimitConfig,
    PromptFilterConfig,
    OutputVerifierConfig,
    SecurityConfig,
    SecurityMiddleware,
    Authenticator,
    PromptFilter,
    OutputVerifier,
)
from .cuda_device import (
    cuda_is_available,
    set_device,
    current_device,
    device_count,
    get_device_name,
    get_device_capability,
    CUDADevice,
    DeviceContext,
    CUDAMemoryPool,
    cuda_memory_summary,
    synchronize,
)
from .cuda_kernels import (
    ComputeCapability,
    KernelConfig,
    TensorDescriptor,
    CUDAStream,
    CUDAEvent,
    KernelLauncher,
    get_launcher,
    gemm_kernel,
    gemm_batched_kernel,
    flash_attention_v2_kernel,
    flash_attention_v2_backward_kernel,
    layernorm_kernel,
    layernorm_backward_kernel,
    rmsnorm_kernel,
    softmax_kernel,
    silu_kernel,
    gelu_kernel,
    relu_kernel,
    dropout_kernel,
    dropout_backward_kernel,
    bias_gelu_kernel,
    fused_adamw_kernel,
    conv2d_kernel,
    _HAS_CUDA_BACKEND,
)
from .checkpoint import (
    CheckpointWriter,
    CheckpointReader,
    CheckpointCoordinator,
    HeartbeatMonitor,
    ElasticTrainer,
    FaultToleranceManager,
    validate_checkpoint,
    CheckpointHeader,
    TensorRecord,
)
from .quantization import (
    QuantMode,
    QuantGranularity,
    quantize_int8_sym,
    dequantize_int8_sym,
    quantize_int8_asym,
    dequantize_int8_asym,
    quantize_int8_channel,
    dequantize_int8_channel,
    quantize_int4_sym,
    dequantize_int4_sym,
    quantize_fp8_e4m3,
    dequantize_fp8_e4m3,
    quantize_fp8_e5m2,
    dequantize_fp8_e5m2,
    awq_scale_weights,
    awq_quantize,
    gptq_compute_hessian,
    gptq_quantize,
    QuantizedLinear,
    quantize_error,
)
from .profiler import (
    Profiler,
    ProfileEntry,
    Timer,
    MemoryTracker,
    TrainProfiler,
    timeit,
    get_profiler,
    _GLOBAL_PROFILER,
)

# Phase 6 — Infrastructure bindings (net + drivers)
from .net_bindings import (
    Topology,
    TopologyType,
    SocketComm,
    RDMA,
    GRPCService,
    NCCLComm,
    ProcessGroup,
)
from .driver_bindings import (
    CUDADriver,
    CUDADeviceProps,
    ROCmDriver,
    TPUDriver,
)

# Phase 7 — ASM integration
from .asm_bridge import (
    CPUFeatures,
    AsmLibrary,
    AsmFunction,
    ConstantTime as AsmConstantTime,
    SecureMemory as AsmSecureMemory,
)
from .crypto_asm import (
    AESNI,
    SHANI,
    ChaCha20AVX2,
    Poly1305ASM,
    MontgomeryMul,
    Ed25519ASM,
    ConstantTimeOps,
    FirewallASM,
)
from .data_loader import (
    Dataset,
    TensorDataset,
    MemoryMappedTextDataset,
    DistributedSampler,
    DataLoader,
    default_collate,
)
from .pruning import (
    magnitude_prune,
    l1_channel_prune,
    taylor_pruning,
    global_magnitude_prune,
    movement_pruning,
    soft_pruning,
    compute_sparsity,
    count_parameters,
    print_pruning_summary,
    apply_pruning_mask,
    recover_pruned_weights,
    distillation_loss,
    prune_and_distill,
    find_winning_ticket,
    rewrite_weights,
)
from .distillation import (
    kd_loss,
    attention_transfer_loss,
    feature_matching_loss,
    correlation_congruence_loss,
    hint_loss,
    crd_loss,
    multi_teacher_distillation_loss,
    ensemble_teacher_distillation,
    OnlineDistillation,
    DistillationPruner,
    distill_bert,
    distill_gpt,
)
from .benchmarking import (
    BenchmarkConfig,
    BenchmarkSuite,
    BenchmarkTimer,
    MemoryTracker,
    BenchmarkResult,
)
from .benchmark import (
    BenchmarkConfig,
    BenchmarkResult,
    BenchmarkSuite,
    run_benchmark_cli,
)
from .vision_transformers import (
    PatchEmbedding,
    ViTBlock,
    VisionTransformer,
    vit_tiny_patch16_224,
    vit_small_patch16_224,
    vit_base_patch16_224,
    vit_large_patch16_224,
    vit_huge_patch14_224,
    MAE,
    mae_base,
    mae_large,
    mae_huge,
    create_vision_model,
)
from .benchmarks import (
    BenchmarkConfig,
    BenchmarkResult,
    BenchmarkSuite,
    BenchmarkTimer,
    MemoryTracker,
    run_benchmarks,
)
from .llama_models import (
    # LLaMA
    LlamaRMSNorm,
    LlamaRotaryEmbedding,
    apply_rotary_pos_emb,
    rotate_half,
    LlamaAttention,
    LlamaMLP,
    LlamaDecoderLayer,
    LlamaModel,
    LlamaForCausalLM,
    # Mistral
    MistralAttention,
    MistralMLP,
    MistralDecoderLayer,
    MistralModel,
    MistralForCausalLM,
    # Qwen2
    Qwen2Attention,
    Qwen2MLP,
    Qwen2DecoderLayer,
    Qwen2Model,
    Qwen2ForCausalLM,
    # DeepSeek V2
    DeepSeekV2Attention,
    DeepSeekV2MLP,
    DeepSeekV2DecoderLayer,
    DeepSeekV2Model,
    DeepSeekV2ForCausalLM,
    # Configs
    LLAMA_CONFIGS,
    MISTRAL_CONFIGS,
    QWEN2_CONFIGS,
    DEEPSEEK_V2_CONFIGS,
    get_model_config,
    create_model,
    create_llama_model,
    create_mistral_model,
    create_qwen2_model,
    create_deepseek_v2_model,
    # Weight loading
    load_hf_weights,
    convert_hf_llama_weights,
)
from .inference_server import (
    app as inference_app,
    register_model,
    get_model,
    list_models,
    GenerateRequest,
    GenerateResponse,
    BatchGenerateRequest,
    BatchGenerateResponse,
    ChatCompletionRequest,
    ChatCompletionResponse,
    HealthResponse,
    ModelInfo,
    ModelListResponse,
)
from .serve_cli import main as serve_main
from .generation import (
    GenerationConfig,
    top_k_top_p_filtering,
    sample,
    Streamer,
    TextStreamer,
    TokenStreamer,
    greedy_search,
    sample_generation,
    beam_search,
    generate,
    batch_generate,
)
from .tokenizer import (
    Tokenizer,
    SimpleTokenizer as TokenizerSimpleTokenizer,
)
from .train import (
    Trainer,
    TrainConfig,
    Optimizer as CppOptimizer,
    SGD as CppSGD,
    Adam as CppAdam,
    AdamW as CppAdamW,
    StepLR,
    ExponentialLR,
    CosineLR,
    ReduceLROnPlateau,
    MSELoss,
    CrossEntropyLoss,
    MAELoss,
    NLLLoss,
    KLDivLoss,
    BCELoss,
    Dataset as CppDataset,
    TensorDataset as CppTensorDataset,
    DataLoader,
)

__all__ = [
    # tensor
    "Tensor",
    "Dtype",
    "Device",
    "Layout",
    "Tensorable",
    "_HAS_C_BACKEND",
    # nn
    "Module",
    "Linear",
    "Embedding",
    "Dropout",
    "LayerNorm",
    "RMSNorm",
    "GELU",
    "SiLU",
    "ReLU",
    "Sigmoid",
    "Tanh",
    "Sequential",
    "MultiheadAttention",
    "TransformerBlock",
    "Transformer",
    # optim
    "Optimizer",
    "SGD",
    "AdamW",
    "Lion",
    "LAMB",
    "LARS",
    "AdaFactor",
    "RAdam",
    "Sophia",
    "Adan",
    "ScheduleFreeAdamW",
    "CosineAnnealingLR",
    # data
    "Dataset",
    "TensorDataset",
    "TextDataset",
    "SimpleTokenizer",
    "BatchCollator",
    "Preprocessor",
    # distributed
    "DistributedContext",
    "DistributedSampler",
    "DistributedDataParallel",
    "init_process_group",
    "destroy_process_group",
    "get_world_size",
    "get_rank",
    "barrier",
    "all_reduce",
    "launch",
    # hf
    "load_hf_model",
    "save_hf_model",
    "load_config",
    # model
    "Model",
    "ModelConfig",
    "HSSModel",
    "HSSConfig",
    "SERModel",
    "SERConfig",
    "ARCModel",
    "ARCConfig",
    "NPEModel",
    "NPEConfig",
    "FMModel",
    "FMConfig",
    # quantization
    "QuantMode",
    "QuantGranularity",
    "quantize_int8_sym",
    "dequantize_int8_sym",
    "quantize_int8_asym",
    "dequantize_int8_asym",
    "quantize_int8_channel",
    "dequantize_int8_channel",
    "quantize_int4_sym",
    "dequantize_int4_sym",
    "quantize_fp8_e4m3",
    "dequantize_fp8_e4m3",
    "quantize_fp8_e5m2",
    "dequantize_fp8_e5m2",
    "awq_scale_weights",
    "awq_quantize",
    "gptq_compute_hessian",
    "gptq_quantize",
    "QuantizedLinear",
    "quantize_error",
    # checkpoint
    "CheckpointWriter",
    "CheckpointReader",
    "CheckpointCoordinator",
    "HeartbeatMonitor",
    "ElasticTrainer",
    "FaultToleranceManager",
    "validate_checkpoint",
    "CheckpointHeader",
    "TensorRecord",
    # profiler
    "Profiler",
    "ProfileEntry",
    "Timer",
    "MemoryTracker",
    "TrainProfiler",
    "timeit",
    "get_profiler",
    "_GLOBAL_PROFILER",
    # model zoo
    "ModelFamily",
    "LlamaConfig",
    "MistralConfig",
    "Qwen2Config",
    "DeepSeekV2Config",
    "get_model_config",
    "config_from_json",
    "list_available_models",
    "read_safetensors",
    "convert_hf_to_sneppx",
    "build_model_from_config",
    "build_transformer_from_config",
    "from_pretrained",
    "HF_WEIGHT_MAP",
    # model implementations
    "BertModel",
    "BertForMaskedLM",
    "BertConfig",
    "GPTModel",
    "GPTLMHeadModel",
    "GPTConfig",
    "T5Model",
    "T5ForConditionalGeneration",
    "T5Config",
    "create_bert_model",
    "create_gpt_model",
    "create_t5_model",
    "get_model_config",
    "count_parameters",
    "get_model_size_mb",
    # augmentation
    "Compose",
    "RandomApply",
    "RandomChoice",
    "RandomOrder",
    "random_resized_crop",
    "random_horizontal_flip",
    "random_vertical_flip",
    "random_rotation",
    "color_jitter",
    "random_grayscale",
    "gaussian_blur",
    "solarize",
    "posterize",
    "auto_contrast",
    "equalize",
    "invert",
    "sharpness",
    "mixup",
    "cutmix",
    "augmix",
    "cutout",
    "random_erasing",
    "random_token_mask",
    "random_word_dropout",
    "random_word_shuffle",
    "token_cutout",
    "time_stretch",
    "pitch_shift",
    "time_mask",
    "freq_mask",
    "center_crop",
    "random_crop",
    "five_crop",
    "ten_crop",
    "IMAGENET_TRAIN_TRANSFORMS",
    "IMAGENET_EVAL_TRANSFORMS",
    "CIFAR10_TRAIN_TRANSFORMS",
    "CIFAR10_EVAL_TRANSFORMS",
    # pruning
    "magnitude_prune",
    "l1_channel_prune",
    "taylor_pruning",
    "global_magnitude_prune",
    "movement_pruning",
    "soft_pruning",
    "compute_sparsity",
    "count_parameters",
    "print_pruning_summary",
    "apply_pruning_mask",
    "recover_pruned_weights",
    "distillation_loss",
    "prune_and_distill",
    "find_winning_ticket",
    "rewrite_weights",
    # distillation
    "kd_loss",
    "attention_transfer_loss",
    "feature_matching_loss",
    "correlation_congruence_loss",
    "hint_loss",
    "crd_loss",
    "multi_teacher_distillation_loss",
    "ensemble_teacher_distillation",
    "OnlineDistillation",
    "DistillationPruner",
    "distill_bert",
    "distill_gpt",
    # vision transformers
    "PatchEmbedding",
    "ViTBlock",
    "VisionTransformer",
    "vit_tiny_patch16_224",
    "vit_small_patch16_224",
    "vit_base_patch16_224",
    "vit_large_patch16_224",
    "vit_huge_patch14_224",
    "MAE",
    "mae_base",
    "mae_large",
    "mae_huge",
    "create_vision_model",
    # benchmarks
    # llama models
    "LlamaRMSNorm",
    "LlamaRotaryEmbedding",
    "apply_rotary_pos_emb",
    "rotate_half",
    "LlamaAttention",
    "LlamaMLP",
    "LlamaDecoderLayer",
    "LlamaModel",
    "LlamaForCausalLM",
    # Mistral
    "MistralAttention",
    "MistralMLP",
    "MistralDecoderLayer",
    "MistralModel",
    "MistralForCausalLM",
    # Qwen2
    "Qwen2Attention",
    "Qwen2MLP",
    "Qwen2DecoderLayer",
    "Qwen2Model",
    "Qwen2ForCausalLM",
    # DeepSeek V2
    "DeepSeekV2Attention",
    "DeepSeekV2MLP",
    "DeepSeekV2DecoderLayer",
    "DeepSeekV2Model",
    "DeepSeekV2ForCausalLM",
    # Configs
    "LLAMA_CONFIGS",
    "MISTRAL_CONFIGS",
    "QWEN2_CONFIGS",
    "DEEPSEEK_V2_CONFIGS",
    "get_model_config",
    "create_model",
    "create_llama_model",
    "create_mistral_model",
    "create_qwen2_model",
    "create_deepseek_v2_model",
    # Weight loading
    "load_hf_weights",
    "convert_hf_llama_weights",
    # Phase 5 inference server
    "inference_app",
    "register_model",
    "get_model",
    "list_models",
    "GenerateRequest",
    "GenerateResponse",
    "BatchGenerateRequest",
    "BatchGenerateResponse",
    "ChatCompletionRequest",
    "ChatCompletionResponse",
    "HealthResponse",
    "ModelInfo",
    "ModelListResponse",
    "serve_main",
    # Phase 4 infrastructure
    "CheckpointManager",
    "DistributedWrapper",
    "estimate_flops",
    # Phase 6 experiment tracking
    "ExperimentRun",
    "LocalBackend",
    "Tracker",
    "LogTracker",
    "ExperimentTracker",
    "WandbTracker",
    "MLflowTracker",
    "CompositeTracker",
    "experiment_cli_main",
    # Phase 7 hyperparameter search
    "Param",
    "UniformFloat",
    "LogUniformFloat",
    "UniformInt",
    "Choice",
    "Fixed",
    "SearchSpace",
    "Trial",
    "Sampler",
    "GridSampler",
    "RandomSampler",
    "BayesianSampler",
    "HPSearchRunner",
    # Differential privacy
    "LaplaceMech",
    "GaussianMech",
    "PrivacyBudget",
    "RDPAccountant",
    "DPSGD",
    # Adversarial robustness
    "Attack",
    "FGSM",
    "PGD",
    "AdversarialExample",
    "AdversarialTrainer",
    # Model watermarking
    "ModelHasher",
    "WeightWatermark",
    "BackdoorWatermark",
    # S5 AI safety bindings
    "S5PromptFilter",
    "S5OutputVerifier",
    "S5RLHFSafety",
    # Security middleware
    "AuthConfig",
    "RateLimitConfig",
    "PromptFilterConfig",
    "OutputVerifierConfig",
    "SecurityConfig",
    "SecurityMiddleware",
    "Authenticator",
    "PromptFilter",
    "OutputVerifier",
    # Phase 8 CUDA device
    "cuda_is_available",
    "set_device",
    "current_device",
    "device_count",
    "get_device_name",
    "get_device_capability",
    "CUDADevice",
    "DeviceContext",
    "CUDAMemoryPool",
    "cuda_memory_summary",
    "synchronize",
    # Phase 9 CUDA kernels
    "ComputeCapability",
    "KernelConfig",
    "TensorDescriptor",
    "CUDAStream",
    "CUDAEvent",
    "KernelLauncher",
    "get_launcher",
    "gemm_kernel",
    "gemm_batched_kernel",
    "flash_attention_v2_kernel",
    "flash_attention_v2_backward_kernel",
    "layernorm_kernel",
    "layernorm_backward_kernel",
    "rmsnorm_kernel",
    "softmax_kernel",
    "silu_kernel",
    "gelu_kernel",
    "relu_kernel",
    "dropout_kernel",
    "dropout_backward_kernel",
    "bias_gelu_kernel",
    "fused_adamw_kernel",
    "conv2d_kernel",
    "_HAS_CUDA_BACKEND",
    # train (C++ backend)
    "Trainer",
    "TrainConfig",
    "CppOptimizer",
    "CppSGD",
    "CppAdam",
    "CppAdamW",
    "StepLR",
    "ExponentialLR",
    "CosineLR",
    "ReduceLROnPlateau",
    "MSELoss",
    "CrossEntropyLoss",
    "MAELoss",
    "NLLLoss",
    "KLDivLoss",
    "BCELoss",
    "CppDataset",
    "CppTensorDataset",
    "DataLoader",
    "_neural_engine_bridge",
    # Phase 1 Foundation — dispatch layer
    "get_backend",
    "get_security_backend",
    "get_algo_backend",
    "get_kernel_backend",
    "get_infra_backend",
    "_HAS_CUDA",
    "_HAS_C",
    "load_library",
    "find_load",
    "int8_t",
    "uint8_t",
    "int16_t",
    "uint16_t",
    "int32_t",
    "uint32_t",
    "int64_t",
    "uint64_t",
    "size_t",
    "ssize_t",
    "float_t",
    "double_t",
    "const_char_p",
    "void_p",
    "DataBuffer",
    "make_struct",
    "dispatch",
    # Phase 2 — Crypto bindings
    "Ed25519",
    "Dilithium",
    "SphincsPlus",
    "KyberKEM",
    "X25519",
    "AESGCM",
    "ChaCha20",
    "Poly1305",
    "AEAD",
    "sha256",
    "sha512",
    "sha3_256",
    "sha3_512",
    "shake_128",
    "shake_256",
    "Blake3",
    "SipHash",
    "HMAC_",
    "HKDF",
    "PBKDF2",
    "Argon2",
    "BigNum",
    "DRBG",
    "Random",
    "ConstantTime",
    "EntropyPool",
    # Phase 3 — Security bindings (S1–S9)
    "SecureAllocator",
    "StackCanary",
    "ASLR",
    "MemoryHardening",
    "MemoryLeakDetector",
    "DDoSMitigation",
    "IdentityManager",
    "TransportSecurity",
    "IntegrityMonitor",
    "ContainerBreakoutDetector",
    "AdvancedMonitor",
    "KeyVault",
    "AuditLogger",
    "SignedUpdate",
    "ContainerSecurity",
    "LTLProperty",
    "ModelChecker",
    "StateGraph",
    "NetworkFuzzer",
    "SelfAuditor",
    "ObfuscationConfig",
    "CfgFlattening",
    "InstructionSubstitution",
    "OpaquePredicate",
    "StringEncryption",
    "ObfuscationPipeline",
    "RLHFSafety",
    "AIPromptFilter",
    "AIOutputVerifier",
    "DataPoisoningDefense",
    # Phase 4 — Algorithm bindings
    "ARCAttackSim",
    "ARCFForward",
    "ARCGradientObfuscator",
    "ARCInputGuard",
    "ARCOutputVerifier",
    "FMController",
    "FMMemoryBank",
    "FMNode",
    "FMSync",
    "HSSDiscretize",
    "HSSScan",
    "AlgoHSSModel",
    "HSSStep",
    "NPEInstruction",
    "NPEProgram",
    "NPECompiler",
    "NPEVM",
    "NPEVerify",
    "SERExpert",
    "SERRoute",
    "SERLayer",
    "SERLoss",
    "AlgoSERModel",
    # Phase 5 — Kernel bindings
    "Attention",
    "DifferentialAttention",
    "FlexAttention",
    "ArchOps",
    "Mamba2",
    "MemoryAllocator",
    "MemoryPool",
    "ThreadPool",
    "WorkStealingPool",
    "TensorExpr",
    "TensorExprCompiler",
    "SimdGemm",
    "GemmConfig",
    "Logger",
    # Phase 6 — Infrastructure bindings
    "Topology",
    "TopologyType",
    "SocketComm",
    "RDMA",
    "GRPCService",
    "NCCLComm",
    "ProcessGroup",
    "CUDADriver",
    "CUDADeviceProps",
    "ROCmDriver",
    "TPUDriver",
    # Phase 7 — ASM integration
    "CPUFeatures",
    "AsmLibrary",
    "AsmFunction",
    "AsmConstantTime",
    "AsmSecureMemory",
    "AESNI",
    "SHANI",
    "ChaCha20AVX2",
    "Poly1305ASM",
    "MontgomeryMul",
    "Ed25519ASM",
    "ConstantTimeOps",
    "FirewallASM",
]
