# Sanitizers module
# Usage: include(Sanitizers) then use target_sanitize(my_target PRIVATE address undefined)

set(_sanitizer_flags "")

function(target_sanitize TARGET)
    cmake_parse_arguments(PARSE_ARGV 1 "" "" "PRIVATE;PUBLIC;INTERFACE" "")
    if(NOT CMAKE_C_COMPILER_ID MATCHES "GNU|Clang|AppleClang")
        return()
    endif()
    set(flags "")
    foreach(mode ${__PRIVATE} ${__PUBLIC} ${__INTERFACE})
        if(mode STREQUAL "address")
            list(APPEND flags "-fsanitize=address")
        elseif(mode STREQUAL "undefined")
            list(APPEND flags "-fsanitize=undefined" "-fsanitize=float-divide-by-zero" "-fsanitize=float-cast-overflow")
        elseif(mode STREQUAL "leak")
            list(APPEND flags "-fsanitize=leak")
        elseif(mode STREQUAL "thread")
            list(APPEND flags "-fsanitize=thread")
        elseif(mode STREQUAL "memory")
            list(APPEND flags "-fsanitize=memory")
        endif()
    endforeach()
    if(flags)
        target_compile_options(${TARGET} PRIVATE ${flags} -g -fno-omit-frame-pointer)
        target_link_options(${TARGET} PRIVATE ${flags})
    endif()
endfunction()
